#!bin/bash

 echo -e '\n\e[42mPreparing to install\e[0m\n' && sleep 1
 cd $HOME
 sudo apt update && sudo apt upgrade -y
 sudo apt install curl -y
 sudo curl https://sh.rustup.rs -sSf | sh -s -- -y
 . $HOME/.cargo/env
 curl https://deb.nodesource.com/setup_16.x | sudo bash
 curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
 echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
 sudo apt install curl make clang pkg-config libssl-dev build-essential git jq nodejs -y
 sudo npm --force install -g yarn
 git clone https://github.com/iron-fish/ironfish.git
 cd ironfish
 yarn install
 cd ironfish-cli
 yarn build
 yarn --cwd ~/ironfish/ironfish-cli/ ironfish config:set blockGraffiti r00tVV
 yarn --cwd ~/ironfish/ironfish-cli/ ironfish config:set enableTelemetry true
